### ISSUE TITLE
Timeout from `ndnpeek`

### ISSUE THREAD

**Issue by chavoosh** [zhehaowang/ndnfs-port#12]
After installing NDNFS-Port, without changing the default configs I simply tried the [usage guidance](https://github.com/remap/ndnfs-port#usage). I tried to fetch `test.txt` file via `ndnpeek` however it experiences timeout.

Output of `ndnpeek`:
```    
INTEREST: /ndn/broadcast/ndnfs/test.txt?ndn.MaxSuffixComponents=1&ndn.MustBeFresh=1
TIMEOUT
```

I tried `ndncatchunks` then to fetch `test.txt` (while providing the version number to make sure no discovery Interest will be sent out) and I could successfully fetch the content.

So, I suspect maybe NDNFS-Port does not properly support `CanBePrefix` option and it requires version to be provided by the consumer.

**Comment by jefft0** [comment]
@chavoosh Can you try the CanBePrefix -P option of ndnpeek?

    ndnpeek -pfP /ndn/broadcast/ndnfs/test.txt

**Comment by jefft0** [comment]
I did a pull request for my small change to ndnpeek to print the Data packet name if Verbose and CanBePrefix. https://github.com/jefft0/ndn-tools

    ndnpeek -pfPv /ndn/broadcast/ndnfs/test.txt

prints

    INTEREST: /ndn/broadcast/ndnfs/test.txt?ndn.MustBeFresh=1
    DATA, RTT: 194ms, Name: /ndn/broadcast/ndnfs/test.txt/%C1.FS.file/%FD%5C%F9L%F3
    <non-printable>

This is a meta packet where the content is the Protobuf encoding of the meta info https://github.com/remap/ndnfs-port/blob/master/server/file.proto. You can then get the correct version, in this case:

    ndnpeek -pfPv /ndn/broadcast/ndnfs/test.txt/%FD%5C%F9L%F3

prints:

    INTEREST: /ndn/broadcast/ndnfs/test.txt/%FD%5C%F9L%F3?ndn.MustBeFresh=1
    DATA, RTT: 3ms, Name: /ndn/broadcast/ndnfs/test.txt/%FD%5C%F9L%F3/%00%00
    Hello, world!

**Comment by chavoosh** [comment]
But still consumer needs to provide the version number otherwise, no Data packet will be sent back. Right? I believe a better behavior is `NDNFS` responds with the first chunk of the content upon receiving an Interest that lacks the version number. Does it make sense to you?

**Comment by jefft0** [comment]
NDNFS was designed so that the consumer should first fetch the meta packet with %C1.FS.file, decode the Protobuf meta info to get the version number, then fetch the version. This is more "deterministic". 

You are proposing that when NDNFS receives an Interest with a prefix like /ndn/broadcast/ndnfs/test.txt, the default behavior should be to return the first segment of the latest version /ndn/broadcast/ndnfs/test.txt/%FD%5C%F9L%F3/%00%00 . The problem is that the NDN protocol does not define which Data packet should be returned for a prefix match. Even if NDNFS does what you expect, a cache in the network might return a different Data packet, such as /ndn/broadcast/ndnfs/test.txt/%C1.FS.file/%FD%5C%F9L%F3 .

**Comment by chavoosh** [comment]
I got it. Your explanation totally makes sense...
